FROM debian
CMD "Instalacion de LAMP"
RUN apt update && apt -y upgrade
RUN apt install apache2 apache2-utils -y
RUN apt install mariadb-server mariadb-cliente -y
RUN apt install php7.3 libapache2-mod-php7.3 php7.3-mysql php-common php7.3-cli php7.3-common php7.3-json php7.3-opcache php7.3-readline -y
RUN apt a2enmod php7.3
RUN apt update && apt -y upgrade
RUN apt install unzip
COPY drupal-8.8.5.zip /var/www/html
WORKDIR /var/www/html
RUN unzip drupal-8.8.5.zip
RUN mkdir /home/drupal
COPY readme.txt /home/drupal
COPY set_parameters.php /home/drupal
WORKDIR /homr/drupal
EXPOSE 3306
EXPOSE 80
